### ISSUE TITLE
无敌船 mod 中船无法被划动

### ISSUE THREAD

**Issue by Coldfeeling** [Sodium-Aluminate/DST-Mods#1]

**Comment by Sodium-Aluminate** [comment]
[#commit/e804d3721445eec1c82c8d393b766ccd4142faab](https://github.com/Sodium-Aluminate/DST-Mods/commit/e804d3721445eec1c82c8d393b766ccd4142faab)

修了，下次有 bug 请扔一下日志说明一下原因，不然我开游戏还得好长时间（

**Comment by Sodium-Aluminate** [comment]
还有我这里复现的结果不是实体无法移动而是游戏因为 nil 而崩溃，你再看看在游戏里是不是划船之后玩家甚至不能走了？

**Comment by Coldfeeling** [comment]
好的，划船后玩家并不会走不动，不过存档退出后重新进入时马上闪退，steam验证游戏完整性后才可以重新进入存档



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月2日(周五) 下午5:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Sodium-Aluminate/DST-Mods] bug boat mod船无法被划动 (Issue #1)




 
#commit/e804d3721445eec1c82c8d393b766ccd4142faab
 
修了，下次有 bug 请扔一下日志说明一下原因，不然我开游戏还得好长时间（

**Comment by Sodium-Aluminate** [comment]
> 好的，划船后玩家并不会走不动，不过存档退出后重新进入时马上闪退，steam验证游戏完整性后才可以重新进入存档

唔，你应该安装错位置了。根据 klei 设置，mod 没有改变游戏本体的权限的

**Comment by Coldfeeling** [comment]
> 还有我这里复现的结果不是实体无法移动而是游戏因为 nil 而崩溃，你再看看在游戏里是不是划船之后玩家甚至不能走了？

貌似还是有问题，无敌船在海上划船行驶正常，一上陆地就直接卡在原地，无法被移动

**Comment by Coldfeeling** [comment]
> > 好的，划船后玩家并不会走不动，不过存档退出后重新进入时马上闪退，steam验证游戏完整性后才可以重新进入存档
> 
> 唔，你应该安装错位置了。根据 klei 设置，mod 没有改变游戏本体的权限的
> 

这个不是mod的问题，是我装的模组冲突了

**Comment by Sodium-Aluminate** [comment]
是我搞错了，现在在 [#commit/75ddc38d4f8d2d2804dce7fd14ac25e1a3cf2699](https://github.com/Sodium-Aluminate/DST-Mods/commit/75ddc38d4f8d2d2804dce7fd14ac25e1a3cf2699) 修了。
